markdown: kramdown
url: ''
baseurl: null
title: Failing Forward
description: Tony E's Journey through Tech and Life.
site-image: /assets/images/meta.jpg
site-keywords: 'Blog, CCIE, Cisco, Wireshark, PCAP, Suricata, Bro, Zeek'
favicon-url: null
heroimage: >-
  https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
twitter_username: showipintbri
github_username: showipintbri
youtube_channel_id: tonyeccie
# Disqus
disqus-shortname: showipintbri
author-name: Tony E.
author-image: /assets/images/tonye.jpg
author-about: >-
  Tony E. is a network security engineer, CCIE# 64908, who loves diving into
  PCAPs, CTF's, Red Team/Blue Team events, going to conferences and meeting
  people in the community to love-life and share.
author-url: 'https://twitter.com/showipintbri'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
  - jemoji
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
